### PR TITLE
WCTE/WCSim compatibility

### PR DESCRIPTION
**Pull request by pdeperio**
Developed and simple runtime test by @akutsuR:

```source envMDT.sh
cd $MDTROOT/cpp; make clean; make all
cd $MDTROOT/app/utilities/WCRootData; make clean; make all
cd $MDTROOT/app/application; make appWCTESingleEvent
cd $MDTROOT
# edit variables properly in run_test_mdt4wcte.sh
bash run_test_mdt4wcte.sh
```
Needs to be validated against regenerated WCSim output before merging.

### CODE REVIEW

**Comment by kmtsui** [comment]
Validation of MDT results. They agree reasonably well with raw WCSIM outputs.
Left: PMT digitized time, right: PMT digitized charge. Black: raw WCSIM output, red: MDT output.

Default WCSim parameters:
image

Varied parameters (with 0.025 x statistics only)

NDigitsThreshold = 25 --> 100
image

NDigitsWindow = 200. --> 1.
image

TimingResConstant_PMT3inchR12199_02= 1.890 --> 3.6
image

TimingResMinimum_PMT3inchR12199_02 = 0.58 --> 1.5
image

DigiHitIntegrationWindow = 200 --> 15
image

**Comment by pdeperio** [comment]
thanks @kmtsui looks good!

can you do a final review and merge if good?

**Review by kmtsui — APPROVED** [review]
Looks good to merge

**Review by kmtsui — APPROVED** [review]

**Comment by pdeperio** [comment]
given all members write access, so you should be able to merge now

**Pull request merged**
